name: .NET Build and Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Build & test
      env:
        KASIOPEA_TEST_BASE: ${{ secrets.KASIOPEA_TEST_BASE }}
        KASIOPEA_TEST_BASICAUTH: ${{ secrets.KASIOPEA_TEST_BASICAUTH }}
        KASIOPEA_TEST_EMAIL: ${{ secrets.KASIOPEA_TEST_EMAIL }}
        KASIOPEA_TEST_PASSWORD: ${{ secrets.KASIOPEA_TEST_PASSWORD }}
      run: dotnet test src/KasiopeaApi.sln -l "console;verbosity=detailed" --configuration Release
