name: Deploy to NuGet

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    environment: nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Pack
      run: dotnet pack src/KasiopeaApi/KasiopeaApi.csproj -c Release -o nupkgs
    - name: Push
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NugetKey }}
